version: "3.4"

services:
  download_data:
    build: 
      context: .
      dockerfile: Dockerfile
      target: final_stage
    image: starvers_eval
    volumes:
      - ${base_host_dir}/rawdata:/starvers_eval/rawdata
      - ./scripts_dev/1_get_and_prepare_data:/starvers_eval/scripts/1_get_and_prepare_data
    entrypoint: [/starvers_eval/scripts/1_get_and_prepare_data/download_data.sh]
  
  construct_datasets:
    build: 
      context: .
      dockerfile: Dockerfile
      target: final_stage
    image: starvers_eval
    volumes:
      - ${base_host_dir}/rawdata:/starvers_eval/rawdata
      - ./scripts_dev/1_get_and_prepare_data:/starvers_eval/scripts/1_get_and_prepare_data
    entrypoint: ["/starvers_eval/python_venv/bin/python3", "-u", "/starvers_eval/scripts/1_get_and_prepare_data/construct_datasets.py"]

  load_data:
    build: 
      context: .
      dockerfile: Dockerfile
      target: final_stage
    image: starvers_eval
    volumes:
      - ${base_host_dir}/rawdata:/starvers_eval/rawdata
      - ${base_host_dir}/databases:/starvers_eval/databases
      - ${base_host_dir}/output/logs:/starvers_eval/output/logs
      - ${base_host_dir}/output/measurements:/starvers_eval/output/measurements
      - ${base_host_dir}/configs:/starvers_eval/configs
      - ./scripts_dev/2_load_data:/starvers_eval/scripts/2_load_data # move to image after development has finished
    environment:
      - triple_stores=${triple_stores}
      - policies=${policies}
      - datasets=${datasets}
    entrypoint: ["/starvers_eval/scripts/2_load_data/create_and_load_triplestores.sh"]
  
  generate_queries:
    build: 
      context: .
      dockerfile: Dockerfile
      target: final_stage
    image: starvers_eval
    volumes:
      - ${base_host_dir}/queries/final_queries:/starvers_eval/queries/final_queries
    entrypoint: ["/starvers_eval/python_venv/bin/python3", "-u", "/starvers_eval/scripts/3_generate_queries/generate_queries.py"]

  evaluate:
    build: 
      context: .
      dockerfile: Dockerfile
      target: final_stage
    image: starvers_eval
    volumes:
      - ${base_host_dir}/configs:/starvers_eval/configs
      - ${base_host_dir}/databases:/starvers_eval/databases
      - ${base_host_dir}/queries/final_queries:/starvers_eval/queries/final_queries
      - ${base_host_dir}/output/logs:/starvers_eval/output/logs
      - ${base_host_dir}/output/measurements:/starvers_eval/output/measurements
      - ${base_host_dir}/output/result_sets:/starvers_eval/output/result_sets
      - ./scripts_dev/4_evaluation:/starvers_eval/scripts/4_evaluation # move to image after development has finished
    hostname: Starvers
    ports:
      - 7200:7200
      - 3030:3030
    environment:
      - policies=${policies}
      - datasets=${datasets}
      - triple_stores=${triple_stores}
      - graphdb_port=${graphdb_port}
      - jenatdb2_port=${jenatdb2_port}
    entrypoint: ["/starvers_eval/scripts/4_evaluation/evaluate.sh"]


