version: "3.4"

services:
  download_data:
    build: 
      context: .
      dockerfile: Dockerfile
      target: final_stage
    image: starvers_eval
    volumes:
      - ~/.starvers_eval/rawdata:/starvers_eval/rawdata
    entrypoint: [/starvers_eval/scripts/1_get_and_prepare_data/download_data.sh]
  
  build_rdf_star_datasets:
    build: 
      context: .
      dockerfile: Dockerfile
      target: final_stage
    image: starvers_eval
    volumes:
      - ~/.starvers_eval/rawdata:/starvers_eval/rawdata
    entrypoint: ["/starvers_eval/python_venv/bin/python3", "-u", "/starvers_eval/scripts/1_get_and_prepare_data/build_tb_rdf_star_datasets.py"]

  load_data:
    build: 
      context: .
      dockerfile: Dockerfile
      target: final_stage
    image: starvers_eval
    volumes:
      - ~/.starvers_eval/rawdata:/starvers_eval/rawdata
      - ~/.starvers_eval/databases:/starvers_eval/databases
      - ~/.starvers_eval/output/logs:/starvers_eval/output/logs
      - ~/.starvers_eval/output/measurements:/starvers_eval/output/measurements
      - ~/.starvers_eval/configs:/starvers_eval/configs
    environment:
      - policies=${policies}
      - datasets=${datasets}
    entrypoint: ["/starvers_eval/scripts/2_load_data/create_and_load_triplestores.sh"]
  
  generate_queries:
    build: 
      context: .
      dockerfile: Dockerfile
      target: final_stage
    image: starvers_eval
    volumes:
      - ~/.starvers_eval/queries/final_queries:/starvers_eval/queries/final_queries
    entrypoint: ["/starvers_eval/python_venv/bin/python3", "-u", "/starvers_eval/scripts/3_generate_queries/generate_queries.py"]

  evaluate:
    build: 
      context: .
      dockerfile: Dockerfile
      target: final_stage
    image: starvers_eval
    volumes:
      - ~/.starvers_eval/configs:/starvers_eval/configs
      - ~/.starvers_eval/databases:/starvers_eval/databases
      - ~/.starvers_eval/queries/final_queries:/starvers_eval/queries/final_queries
      - ~/.starvers_eval/output/logs:/starvers_eval/output/logs
      - ~/.starvers_eval/output/measurements:/starvers_eval/output/measurements
      - ~/.starvers_eval/output/result_sets:/starvers_eval/output/result_sets
    hostname: Starvers
    ports:
      - 7200:7200
      - 3030:3030
    environment:
      - policies=${policies}
      - datasets=${datasets}
      - triple_stores=${triple_stores}
      - graphdb_port=${graphdb_port}
      - jenatdb2_port=${jenatdb2_port}
    entrypoint: ["/starvers_eval/scripts/4_evaluation/evaluate.sh"]


