version: "3.0"

services:
  download_data:
    build: 
      context: .
      dockerfile: Dockerfile
    image: starvers_eval
    volumes:
      - ~/.starvers_eval/rawdata:/starvers_eval/rawdata
    entrypoint: [/starvers_eval/scripts/1_get_and_prepare_data/download_data.sh]