# TODO: Link all scripts to this golden source
[beara]
    snapshot_versions = 58
    [beara.repositories]
        ic_mr_tr = 58
        cb_mr_tr = 116
        ic_sr_ng = 1
        cb_sr_ng = 1
        tb_sr_ng = 1
        tb_sr_rs = 1
    [beara.query_sets]
        [beara.query_sets.high]
            [beara.query_sets.high.policies]
                ic_mr_tr = {versions = 1, template = "ictr/ts"}
                cb_mr_tr = {versions = 1, template = "ictr/ts"}
                ic_sr_ng = {versions = 58, template = "icng/ts"}
                cb_sr_ng = {versions = 58, template = "ictr/ts"}
                tb_sr_ng = {versions = 58, template = "tbng/ts"}
                tb_sr_rs = {versions = 58, template = "ictr/ts"}
        [beara.query_sets.low]
            [beara.query_sets.low.policies]
                ic_mr_tr = {versions = 1, template = "ictr/ts"}
                cb_mr_tr = {versions = 1, template = "ictr/ts"}
                ic_sr_ng = {versions = 58, template = "icng/ts"}
                cb_sr_ng = {versions = 58, template = "ictr/ts"}
                tb_sr_ng = {versions = 58, template = "tbng/ts"}
                tb_sr_rs = {versions = 58, template = "ictr/ts"}

[bearb_hour]
    snapshot_versions = 1299
    [bearb_hour.repositories]
        ic_mr_tr = 1299
        cb_mr_tr = 2598
        ic_sr_ng = 1
        cb_sr_ng = 1
        tb_sr_ng = 1
        tb_sr_rs = 1
    [bearb_hour.query_sets]
        [bearb_hour.query_sets.join]
            [bearb_hour.query_sets.join.policies]
                ic_mr_tr = {versions = 1, template = "ic/bgp"}
                cb_mr_tr = {versions = 1, template = "ic/bgp"}
                ic_sr_ng = {versions = 1299, template = "icng/bgp"}
                cb_sr_ng = {versions = 1299, template = "ictr/bgp"}
                tb_sr_ng = {versions = 1299, template = "tbng/bgp"}
                tb_sr_rs = {versions = 1299, template = "ictr/bgp"}
        [bearb_hour.query_sets.lookup]
            [bearb_hour.query_sets.lookup.policies]
                ic_mr_tr = {versions = 1, template = "ictr/ts"}
                cb_mr_tr = {versions = 1, template = "ictr/ts"}
                ic_sr_ng = {versions = 1299, template = "icng/ts"}
                cb_sr_ng = {versions = 1299, template = "ictr/ts"}
                tb_sr_ng = {versions = 1299, template = "tbng/ts"}
                tb_sr_rs = {versions = 1299, template = "ictr/ts"}

[bearb_day]
    snapshot_versions = 89
    [bearb_day.repositories]
        ic_mr_tr = 89
        cb_mr_tr = 178
        ic_sr_ng = 1
        cb_sr_ng = 1
        tb_sr_ng = 1
        tb_sr_rs = 1
    [bearb_day.query_sets]
        [bearb_day.query_sets.join]
            [bearb_day.query_sets.join.policies]
                ic_mr_tr = {versions = 1, template = "ic/bgp"}
                cb_mr_tr = {versions = 1, template = "ic/bgp"}
                ic_sr_ng = {versions = 1299, template = "icng/bgp"}
                cb_sr_ng = {versions = 1299, template = "ictr/bgp"}
                tb_sr_ng = {versions = 1299, template = "tbng/bgp"}
                tb_sr_rs = {versions = 1299, template = "ictr/bgp"}
        [bearb_day.query_sets.lookup]
            [bearb_day.query_sets.lookup.policies]
                ic_mr_tr = {versions = 1, template = "ictr/ts"}
                cb_mr_tr = {versions = 1, template = "ictr/ts"}
                ic_sr_ng = {versions = 1299, template = "icng/ts"}
                cb_sr_ng = {versions = 1299, template = "ictr/ts"}
                tb_sr_ng = {versions = 1299, template = "tbng/ts"}
                tb_sr_rs = {versions = 1299, template = "ictr/ts"}

[bearc]
    snapshot_versions = 33
    [bearc.repositories]
        ic_mr_tr = 33
        cb_mr_tr = 66
        ic_sr_ng = 1
        cb_sr_ng = 1
        tb_sr_ng = 1
        tb_sr_rs = 1
    [bearc.query_sets]
        [bearc.query_sets.complex]
            [bearc.query_sets.complex.policies]
                ic_mr_tr = {versions = 1, template = "ic/sparql"}
                cb_mr_tr = {versions = 1, template = "ic/sparql"}
                ic_sr_ng = {versions = 33, template = "icng/sparql"}
                cb_sr_ng = {versions = 33, template = "ictr/sparql"}
                tb_sr_ng = {versions = 33, template = "tbng/sparql"}
                tb_sr_rs = {versions = 33, template = "ictr/sparql"}
       