version: "3"

services:
  graphdb_load: 
    logging:
      driver: none
    container_name: starvers_graphdb_${policy}_${dataset}
    build: 
      context: .
      dockerfile: graphdb.Dockerfile
    image: starvers/ontotext/graphdb:9.11.2-se # serves only as a label
    volumes:
      - ./configs/graphdb-config.ttl:/opt/graphdb/home/conf/graphdb-config.ttl
      - ~/.BEAR/databases/graphdb_${policy}_${dataset}/data:/opt/graphdb/home/data
      - ~/.BEAR/rawdata/${dataset}:/opt/graphdb/home/graphdb-import
    entrypoint: ["/opt/graphdb/dist/bin/preload", "-c", "/opt/graphdb/home/conf/graphdb-config.ttl", "/opt/graphdb/home/graphdb-import/${rel_path_import_file}", "--force"]

  jenatdb2_load:
    container_name: starvers_jenatdb2_${policy}_${dataset}
    image: stain/jena-fuseki:4.0.0
    volumes: 
      - ~/.BEAR/databases/jenatdb2_${policy}_${dataset}:/var/data/out/
      - ~/.BEAR/rawdata/${dataset}:/var/data/in/
    entrypoint: ["/jena-fuseki/tdbloader2", "--loc", "/var/data/out/${repositoryID}", "/var/data/in/${rel_path_import_file}"]
